import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "@/theme/global-styles.css";
import { dir } from "i18next";
import { Nprogress } from "@/components/common";
import { LANGUAGES } from "@/constants";
import { DEFAULT_LANGUAGE } from "@/config";

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  themeColor: "black",
  width: "device-width",
  initialScale: 1,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "favicon.ico",
};

export function generateStaticParams() {
  return {
    lng: "fa",
  };
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html lang={DEFAULT_LANGUAGE} dir={dir(DEFAULT_LANGUAGE)} className="html">
      <body className={inter.className + "body"}>
        <Nprogress />
        {children}
      </body>
    </html>
  );
}
