import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";

const roboto = Roboto({ weight: "700", subsets: ["latin"] });

export const metadata: Metadata = {
  viewport: "1",
  title: "Layout",
  description: "Generated by create next app",
  icons: "favicon.ico",
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main>{children}</main>;
}
